#
## Application Properties
#

logger:
  format: ":date[iso] :method :url :status :response-time msec :res[content-length] bytes"

server:
  port: 9000
  public: "public"    # location of static resources

oauth:
  protected-resource: "http://localhost:9002/resource"