env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-console:
    - off         # used for logging
  quotes:
    - error
    - double
  semi:
    - error
    - always
