env:
  es6: true
  browser: true

globals:
  angular: false # false means disallow overwriting

extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-console:
    - off
  quotes:
    - error
    - double
    - allowTemplateLiterals: true
  semi:
    - error
    - always